export const majorCountries = [
    "United States",
    "China",
    "India",
    "Indonesia",
    "Pakistan",
    "Brazil",
    "Nigeria",
    "Bangladesh",
    "Russia",
    "Mexico",
    "Japan",
    "Ethiopia",
    "Philippines",
    "Egypt",
    "Vietnam",
    "DR Congo",
    "Turkey",
    "Iran",
    "Germany",
    "Thailand",
    "United Kingdom",
    "France",
    "Italy",
    "Tanzania",
    "South Africa",
    "Myanmar",
    "South Korea",
    "Colombia",
    "Kenya",
    "Spain",
    // Adding major Arab countries
    "Saudi Arabia",
    "United Arab Emirates",
    "Egypt",
    "Iraq",
    "Qatar",
    "Kuwait",
    "Oman",
    "Bahrain",
    "Jordan",
    "Lebanon"
  ];

  export const pakistanCities = [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Gujranwala",
    "Hyderabad",
    "Peshawar",
    "Quetta",
    "Sialkot",
    "Bahawalpur",
    "Sargodha",
    "Sukkur",
    "Larkana",
    "Sheikhupura",
    "Mirpur Khas",
    "Rahim Yar Khan",
    "Gujrat",
    "Jhang",
    "Mardan",
    "Kasur",
    "Dera Ghazi Khan",
    "Sahiwal",
    "Nawabshah",
    "Mingora",
    "Okara",
    "Mandi Bahauddin",
    "Chiniot",
    "Kamoke",
    "Sadiqabad",
    "Burewala",
    "Jacobabad",
    "Muridke",
    "Jhelum",
    "Shikarpur",
    "Hafizabad",
    "Kohat",
    "Khanewal",
    "Dadu",
    "Gojra",
    "Muzaffargarh",
    "Khuzdar",
    "Pakpattan",
    "Vehari",
    "Chaman",
    "Kot Addu",
    "Attock",
    "Mansehra",
    "Layyah",
    "Swabi",
    "Chakwal",
    "Taxila",
    "Mianwali",
    "Mandi",
    "Turbat",
    "Wah Cantonment",
    "Kasur",
    "Chishtian",
    "Dera Ismail Khan",
    "Chakwal",
    "Kamalia",
    "Umerkot",
    "Ahmedpur East",
    "Kotli",
    "Jaranwala",
    "Sahiwal",
    "Sanghar",
    "Kandhkot",
    "Gujranwala",
    "Dera Allahyar",
    "Tank",
    "Nowshera",
    "Khairpur",
    "Dera Murad Jamali",
    "Leiah",
    "Musa Khel Bazar",
    "Jauharabad",
    "Havelian",
    "Alipur",
    "Mianwali",
    "Charsadda",
    "Tando Allahyar",
    "Pind Dadan Khan",
    "Jhelum",
    "Nankana Sahib",
    "Tando Adam",
    "Kamber Ali Khan",
    "Kotli Loharan",
    "Shahdadkot",
    "Shikarpur",
    "Hala",
    "Khuzdar",
    "Khanpur",
    "Kotri",
    "Bhakkar",
    "Dipalpur",
    "Badin",
    "Arifwala",
    "Pakpattan",
    "Ghotki",
    "Sambrial",
    "Jatoi",
    "Haroonabad",
    "Kashmore",
    "Daska",
    "Rajanpur",
    "Lodhran",
    "Turbat",
    "Shahdadpur",
    "Mehar",
    "Thatta",
    "Bannu",
    "Shakargarh",
    "Hujra Shah Muqim",
    "Matiari",
    "Tando Muhammad Khan",
    "Thatta",
    "Dipalpur",
    "Kandiaro",
    "Kahror Pakka",
    "Gujar Khan",
    "Tando Jam",
    "Renala Khurd",
    "Kanganpur",
    "Gambat",
    "Lakki Marwat",
    "Kahna Nau",
    "Kallar Kahar",
    "Sharqpur Sharif",
    "Lala Musa",
    "Sarai Alamgir",
    "Chichawatni",
    "Rohri",
    "Tando Ghulam Ali",
    "Usta Muhammad",
    "Kot Samaba",
    "Raiwind",
    "Gharo",
    "Pishin",
    "Sehwan",
    "Chunian",
    "Toba Tek Singh",
    "Haveli Lakha",
    "Mustafabad",
    "Kot Radha Kishan",
    "Kunri",
    "Loralai",
  ]

  export const Sects=[
    "Sunni",
    "Shia",
    "Deobandi",
    "Brelvi",
    "Ahle-e-hadees",
    "Other"
  ]

  export const majorCastes = ["Malik", "Awan", "Jutt", "Rajput", "Gujjar", "Syed", "Sheikh", "Butt", "Khan", "Chaudhry", "Arain", "Mirza", "Rana", "Qureshi", "Khattak", "Khokhar", "Abbasi", "Satti", "Dogar", "Mughal"];

  